### ISSUE TITLE
Create dashboard data repo for Cabinet House

### ISSUE THREAD

**Issue by pwalsh** [okfn/spend-publishing-dashboard#15]
## Tasks
- [x] Scrape sources from http://data.gov.uk/api/2/rest/package/financial-transactions-data-co
- [x] Make README, which instructions on the scraped data, and running spd-admin
- [x] Make new data repo ( => gb-spend-25k-cabinet-office)
- [x] Run psd-admin and deploy data

**Comment by pwalsh** [comment]
Requested cabinetoffice.dashboards.okfnlabs.org

**Comment by pwalsh** [comment]
Data is here: https://github.com/okfn/spd-data-uk-cabinet-office
