### ISSUE TITLE
Remove the pricing page

### ISSUE THREAD

**Issue by pwalsh** [okfn/spend-publishing-dashboard#69]
# Tasks
- [x] Remove the code for the actual pricing page
- [x] Keep the "Pricing" menu item, but make it redirect to a dedicated landing page for dashboards
- [x] Have an environment variable so that any user of the open source codebase can remove the "Pricing" item from the menu (`SHOW_PRICING_IN_MENU` `true || false`)

**Comment by georgiana-b** [comment]
@pwalsh  Do we have a link to the "dedicated landing page for dashboards"?

**Comment by pwalsh** [comment]
Just put it in an environment variable, which will be a URL.
